# docker-compose.yml
version: "3"
volumes:
  database_data:
    external: true
  redis_data:
    external: true

services:
  app:
    container_name: swapi-app
    restart: always
    build: .
    links:
      - postgres
      - redis
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://wqopvhiv:j_rXyLzWCFjHV_IsUbgfU6ReWjdXu1Sl@salt.db.elephantsql.com:5432/wqopvhiv
      REDIS_URL: redis://swapi_redis
      NODE_ENV: development
      PORT: 3000
    command: >
      ash -c "npm run migrations && npm run serve"
    ports:
      - "8000:3000"
    command: npm run serve
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:11.5
    expose:
      - '5432'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wqopvhiv
      POSTGRES_PASSWORD: j_rXyLzWCFjHV_IsUbgfU6ReWjdXu1Sl
      POSTGRES_DB: wqopvhiv
      POSTGRES_DB_HOST: salt.db.elephantsql.com
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wqopvhiv']
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    container_name: swapi_redis
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    expose:
      - 6379

