# docker-compose.yml
version: "3"
volumes:
  database_data:
    external: true
  redis_data:
    external: true

services:
  app:
    container_name: swapi-app
    restart: always
    build: .
    links:
      - postgres
      - redis
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/swapi
      REDIS_URL: redis://swapi_redis
      NODE_ENV: development
      PORT: 3000
    command: >
      ash -c "npm run migrations-up:dev && npm run serve"
    ports:
      - "8000:3000"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:11.5
    expose:
      - '5432'
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swapi
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    container_name: swapi_redis
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    expose:
      - 6379
